#!/usr/bin/env python3
"""The committed b9 to b10 artifacts must still be what the tools emit today.

`workspace/outputs/parity/parity_b9.json` / `parity_b10.json` and
`workspace/outputs/diffs/b9-to-b10-20260920.md` are cited as evidence by the
docs, so they go stale the moment a lens, a format, or a hash changes (the
report was regenerated by hand when the depot lens was added). This gate
re-runs both and diffs, normalising only the generation timestamp.

Machine-local by design: it SKIPs unless the live DLL is the studied build, the
retained backup is the old build named in the report, and the cached depot
manifests are present. Regenerate with:

  MONO_PATH=tools/bin mono tools/bin/ParitySurface.exe <dll> | sed -n '/^{/,$p' \\
    > workspace/outputs/parity/parity_<label>.json
  python3 tools/research_diff.py --pair b9:b10

Usage: python3 tools/tests/test_committed_diff_artifacts.py
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _common

REPO = _common.REPO
PAIR = "b9:b10"
SHA_ROW_RE = re.compile(r"^\| sha256 \| `([0-9a-f]{64})` \| `([0-9a-f]{64})` \|$", re.M)
GENERATED_RE = re.compile(r"^Generated \S+ by `tools/research_diff\.py`\.$", re.M)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def committed_report() -> Path | None:
    hits = sorted((REPO / "workspace" / "outputs" / "diffs").glob("b9-to-b10-*.md"))
    return hits[0] if len(hits) == 1 else None


def normalise(text: str) -> str:
    return GENERATED_RE.sub("Generated <stamp> by `tools/research_diff.py`.", text)


def parity_snapshot(dll: Path) -> dict[str, object]:
    env = dict(os.environ, MONO_PATH=str(_common.BIN))
    proc = subprocess.run(
        ["mono", str(_common.BIN / "ParitySurface.exe"), str(dll)],
        capture_output=True,
        text=True,
        env=env,
    )
    assert proc.returncode == 0, proc.stderr
    return json.loads(proc.stdout[proc.stdout.index("{") :])  # type: ignore[no-any-return]


def main() -> int:
    report = committed_report()
    if report is None:
        print("SKIP: no single committed b9-to-b10 report")
        return 0
    asm = _common.find_asm()
    if asm is None:
        print("SKIP: dedicated Assembly-CSharp.dll not found")
        return 0
    backup = asm.with_name(asm.name + ".re_stock_bak")
    if not backup.is_file():
        print(f"SKIP: retained baseline build not found: {backup.name}")
        return 0
    if shutil.which("mono") is None or not (_common.BIN / "ParitySurface.exe").is_file():
        print("SKIP: mono or parity tools not available")
        return 0

    text = report.read_text(encoding="utf-8")
    row = SHA_ROW_RE.search(text)
    if row is None:
        print("SKIP: committed report has no sha256 identity row")
        return 0
    old_sha, new_sha = row.group(1), row.group(2)
    if sha256_file(backup) != old_sha:
        print(f"SKIP: {backup.name} is not the report's baseline build")
        return 0
    if sha256_file(asm) != new_sha:
        print("SKIP: the live DLL is not the report's candidate build")
        return 0

    problems: list[str] = []
    for label, dll in ((PAIR.split(":")[0], backup), (PAIR.split(":")[1], asm)):
        snapshot = REPO / "workspace" / "outputs" / "parity" / f"parity_{label}.json"
        if not snapshot.is_file():
            print(f"SKIP: {snapshot.name} missing")
            return 0
        fresh = parity_snapshot(dll)
        if json.loads(snapshot.read_text(encoding="utf-8")) != fresh:
            problems.append(
                f"{snapshot.relative_to(REPO)} is STALE (regenerate from {dll.name} with ParitySurface)"
            )

    fresh_report = subprocess.run(
        [
            sys.executable,
            str(_common.TOOLS / "research_diff.py"),
            "--pair",
            PAIR,
            "--out",
            "-",
        ],
        capture_output=True,
        text=True,
        env=dict(os.environ, MONO_PATH=str(_common.BIN)),
    )
    if fresh_report.returncode != 0:
        print(f"FAIL: research_diff --pair {PAIR} failed:\n{fresh_report.stderr}", file=sys.stderr)
        return 1
    regenerated = fresh_report.stdout[fresh_report.stdout.index("# Build diff:") :]
    if normalise(regenerated) != normalise(text):
        problems.append(
            f"{report.relative_to(REPO)} is STALE (regenerate with research_diff.py --pair {PAIR})"
        )

    if problems:
        for problem in problems:
            print(f"FAIL: {problem}", file=sys.stderr)
        return 1
    print("OK: committed parity snapshots and b9 to b10 report match the live tools")
    return 0


if __name__ == "__main__":
    sys.exit(main())
